// Walk dist/, bin/, and src/server/session-init.bash, then emit
// src/server/embedded.generated.ts so `bun build --compile` bundles every asset
// into the standalone binary. Run from the repo root.

import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const REPO = process.cwd();
const DIST = join(REPO, "dist");
const GOTTY = join(REPO, "bin/gotty");
const INIT = join(REPO, "src/server/session-init.bash");
const OUT = join(REPO, "src/server/embedded.generated.ts");

const STUB = [
  "// @ts-nocheck",
  "// AUTO-GENERATED stub. `scripts/gen-embed.ts` overwrites this during",
  "// `make compile` with imports of every dist/ asset + bin/gotty + session-init,",
  "// so the compiled binary is fully self-contained. In dev these maps stay empty",
  "// and the server falls back to reading from disk.",
  "export const SPA_FILES: Record<string, string> = {};",
  "export const GOTTY_EMBED: string | null = null;",
  "export const SESSION_INIT_EMBED: string | null = null;",
  "export const SESSION_INIT_ZSH_EMBED: string | null = null;",
  "",
].join("\n");

if (process.argv.includes("--stub")) {
  writeFileSync(OUT, STUB);
  console.log(`[gen-embed] reset ${OUT} to dev stub`);
  process.exit(0);
}

if (!existsSync(DIST)) {
  console.error("[gen-embed] dist/ missing — run `bun run build` first");
  process.exit(1);
}
if (!existsSync(GOTTY)) {
  console.error("[gen-embed] bin/gotty missing — run `bun scripts/install-gotty.ts` first");
  process.exit(1);
}

function walk(dir: string, acc: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) walk(full, acc);
    // Skip the compiled binary itself if a previous run left one behind.
    else if (full !== join(DIST, "tabterm")) acc.push(full);
  }
  return acc;
}

// URL path = path relative to dist/, with a leading "/". Module path = relative
// from src/server/ to the source file, used in the generated import.
const spa = walk(DIST).map((abs, i) => ({
  ident: `_spa${i}`,
  urlPath: "/" + relative(DIST, abs).split(/[\\/]/).join("/"),
  modulePath: "../../" + relative(REPO, abs).split(/[\\/]/).join("/"),
}));

const lines: string[] = [
  "// @ts-nocheck",
  "// AUTO-GENERATED by scripts/gen-embed.ts. Do not edit.",
  "",
];
for (const f of spa) lines.push(`import ${f.ident} from "${f.modulePath}" with { type: "file" };`);
lines.push(`import _gotty from "../../bin/gotty" with { type: "file" };`);
lines.push(`import _init from "./session-init.bash" with { type: "file" };`);
lines.push(`import _initZsh from "./session-init.zsh" with { type: "file" };`);
lines.push("");
lines.push("export const SPA_FILES: Record<string, string> = {");
for (const f of spa) lines.push(`  "${f.urlPath}": ${f.ident},`);
lines.push("};");
lines.push("export const GOTTY_EMBED: string | null = _gotty;");
lines.push("export const SESSION_INIT_EMBED: string | null = _init;");
lines.push("export const SESSION_INIT_ZSH_EMBED: string | null = _initZsh;");
lines.push("");

writeFileSync(OUT, lines.join("\n"));
console.log(`[gen-embed] wrote ${OUT} (${spa.length} SPA files + gotty + init)`);
